version: "3.7"

services:
    service:
        build: ./service
        ports:
            - 5000:5000
        command: --host="0.0.0.0" --name="test-instance" --monitoring="ws://monitoring:8080/listener"
        depends_on:
            - monitoring

    monitoring:
        build: ./monitoring
        ports:
            - 8080:8080


