version: "3.7"

services:
    load-balancer:
        build: ./balancer
        ports:
            - 4000:4000

    service:
        build: ./service
        ports:
            - 5001-5100:5000

    monitoring:
        build: ./monitoring
        ports:
            - 8080:8080

